# Generated by Django 2.1.5 on 2019-01-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arhnapp', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cell',
            field=models.CharField(choices=[('core', 'CORE'), ('wdct', 'WDCT'), ('ecell', 'ECELL'), ('robo', 'ROBO'), ('rd&i', 'RD&I')], default='wdct', max_length=6),
            preserve_default=False,
        ),
    ]
