# Generated by Django 2.1.5 on 2019-01-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arhnapp', '0003_member_cell'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('string', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
    ]
