# Generated by Django 2.1.5 on 2019-01-21 06:23

import arhnapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arhnapp', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=arhnapp.models.slide_image_path)),
                ('slide_link', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Slideshow',
            },
        ),
    ]
