# Generated by Django 2.1.5 on 2019-01-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arhnapp', '0005_slideshow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Date',
        ),
        migrations.AddField(
            model_name='feedback',
            name='event',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
