# Generated by Django 2.1.5 on 2019-01-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arhnapp', '0006_auto_20190124_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.TextField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='event_link',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='event_link_name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
