# Generated by Django 2.1.5 on 2019-01-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arhnapp', '0007_auto_20190124_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cell',
            field=models.CharField(choices=[('core', 'CORE'), ('wdct', 'WDCT'), ('e-cell', 'E-CELL'), ('robo', 'ROBO'), ('r&d', 'R&D')], max_length=6),
        ),
    ]
