# Generated by Django 2.1.5 on 2019-01-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arhnapp', '0008_auto_20190124_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='post',
            field=models.CharField(max_length=25),
        ),
    ]
