# Generated by Django 2.1.5 on 2019-01-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arhnapp', '0009_auto_20190124_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='post',
            field=models.CharField(max_length=40),
        ),
    ]
