# Generated by Django 2.1.5 on 2019-01-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arhnapp', '0010_auto_20190124_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
