# Generated by Django 2.1.5 on 2019-01-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arhnapp', '0013_auto_20190128_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlappyBird',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'FlappyBird',
            },
        ),
    ]
