# Generated by Django 2.1.5 on 2019-02-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arhnapp', '0015_events_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
