# Generated by Django 2.1 on 2019-10-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arhnapp', '0016_slideshow_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_link',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_link_name',
            field=models.CharField(max_length=45),
        ),
    ]
