# Generated by Django 2.1.5 on 2019-12-27 20:26

import arhnapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arhnapp', '0017_auto_20191026_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('image', models.ImageField(upload_to=arhnapp.models.playzone_image_path)),
                ('order', models.IntegerField()),
                ('link', models.CharField(max_length=555)),
            ],
        ),
    ]
